# These are supported funding model platforms

github: Replace [ribeiroednilson1234]
patreon: Replace with a single Patreon ribeiroednilson1234/
open_collective: Replace with a single Open Collective ribeiroednilson1234/
ko_fi: Replace with a single Ko-fi ribeiroednilson1234/
tidelift: Replace with a single Tidelift platform-name/Campanha Política2024 e.g., npm/babel
community_bridge: Replace with a single Community Bridge Campanha Política2024/.git e.g., cloud-foundry
liberapay: Replace with a single Liberapay ribeiroednilson1234/
issuehunt: Replace with a single IssueHunt ribeiroednilson1234/
lfx_crowdfunding: Replace with a single LFX Crowdfunding Campanha Política2024/.git e.g., cloud-foundry
polar: Polar ribeiroednilson1234/
buy_me_a_coffee: Replace with a single Buy Me a Coffee ribeiroednilson1234/
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
